// File generated manually from google-services.json + GoogleService-Info.plist
// (normally auto-generated by `flutterfire configure`).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'this app only targets Android and iOS for now.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg7kyJ8DkjacdlA26dITz-ZgcRsCnRlao',
    appId: '1:85488542124:android:55b9b28656990cff4c9a09',
    messagingSenderId: '85488542124',
    projectId: 'el-ameed-travel',
    storageBucket: 'el-ameed-travel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB5z5e3EoLTczwSMMfI9TmADxp7j2JwWk',
    appId: '1:85488542124:ios:7fdb56b20cfaaf994c9a09',
    messagingSenderId: '85488542124',
    projectId: 'el-ameed-travel',
    storageBucket: 'el-ameed-travel.firebasestorage.app',
    iosBundleId: 'com.company.alameed',
  );
}
